CREATE DATABASE VEICULOS;
USE VEICULOS;           
   
CREATE TABLE VEICULOS(
	ID_VEICULOS VARCHAR(8),
    VEI_PLACA VARCHAR(20),
	VEI_MARCA VARCHAR(20),
    VEI_MODELO VARCHAR(20),
    
    VEI_ANO VARCHAR(6),
    VEI_COR VARCHAR(20),
    VEI_CHASSIS VARCHAR(30),
    PRIMARY KEY(ID_VEICULOS)
);



INSERT INTO VEICULOS(ID_VEICULOS, VEI_PLACA, VEI_MARCA, VEI_MODELO, VEI_ANO, VEI_COR)
VALUES (1, 'AAA 1234', 'FIAT', 'CAMINHONETE TORO', '2023' , 'BRANCO'),
	   (2, 'BBB 1234', 'HUNDAY', 'HB20 1,6', '2022', 'PRATA'),
	   (3, 'CCC 1234', 'CHEVROLET', 'ONIX TURBO 1,6', '2022', 'CINZA'),
	   (4, 'DDD 1234', 'VOLVO', 'BASCULANTE', '2022', 'VERMELHO');
       
SELECT * FROM VEICULOS;
DELETE FROM VEICULOS WHERE ID_VEICULOS = 04;
ALTER TABLE VEICULOS MODIFY COLUMN CHASSIS VARCHAR(20);
ALTER TABLE VEICULOS DROP COLUMN VEI_CHASSIS; 
SELECT * FROM VEICULOS; 
DROP TABLE VEICULOS;

CREATE TABLE VENDEDOR(
	ID_VENDEDOR VARCHAR(14),
    VEN_NOME VARCHAR(40),
    VEN_SALARIO FLOAT,
    VEN_COMISSAO FLOAT,
    PRIMARY KEY(ID_VENDEDOR)
);

INSERT INTO VENDEDOR
(ID_VENDEDOR,VEN_NOME,VEN_SALARIO, VEN_COMISSÃO)
values (01,"JOÃO PEDRO",2300, 10),
       (02,"MARIA LUNA",2300, 10),
	   (03,"JAQUELINE",1700, 10);
       
SELECT * FROM VENDEDOR;
    
CREATE TABLE CLIENTES(
	CLI_NOME VARCHAR(40),
    CLI_ENDEREÇO VARCHAR(40),
    CLI_BAIRRO VARCHAR(20),
    CLI_CIDADE VARCHAR(20),
    CLI_UF VARCHAR(2),
	CLI_CEP VARCHAR(9),
	CLI_TELEFONE VARCHAR(25)
);

insert into CLIENTES 
(ID_CLIENTE, CLI_NOME, CLI_ENDEREÇO, CLI_BAIRRO, CLI_CIDADE, CLI_UF, CLI_CEP, CLI_TELEFONE)
values (01,"EDGAR","RUA 10", "PAULISTANO","SÃO PAULO","SP","01234-000","91234-5678"),
       (02,"EDILSE","RUA 10", "PAULISTANO", "SÃO PAULO", "SP", "012345-000","92345-6789"),
       (03,"LORENA","rUA 10", "PAULISTA", "SÃO PAULO", "SP", "01234-000","93456-7890");
       
       #Altera o Campo CLI_BAIRRO para PAULISTANO
       
       CREATE TABLE NOTA_FISCAL(
       ID_NFISCAL INT,
       ID_VEICULOS INT,
       ID_CLIENTES INT,
       primary key (ID_NFISCAL),
       foreign key(ID_VEICULOS) REFERENCES VEICULOS(ID_VEICULOS),
       foreign key(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
       foreign key(ID_CLIENTES) REFERENCES CLIENTES(ID_CLIENTES));
       
         INSERT INTO NOTA_FISCAL
       (ID_NFISCAL, ID_VEICULOS, ID_VENDEDOR, ID_CLIENTES)
       VALUES( 1, 1, 1, 1),
             ( 2, 2, 2, 2),
             ( 3, 3, 3, 3);
             
	SELECT * FROM NOTA_FISCAL;
    
    SELECT NOTA_FISCAL.ID_VEICULOS, NOTA_FISCAL.ID_VENDEDOR, NOTA_FISCAL.ID_CLIENTES
    FROM NOTA_FISCAL, VENDEDOR, VEICULOS, CLIENTES
    WHERE NOTA_FISCAL.ID_NFISCAL = 2;
    
    SELECT*FROM VEICULOS;
    SELECT * FROM CLIENTES;
    SELECT*FROM VENDEDOR;
    SELECT*FROM NOTA_FISCAL;
    
    SELECT NOTA_FISCAL.ID_VEICULOS, VEICULOS.VEI_PLACA, VEICULOS.VEI_MARCA, VEICULOS.VEI_MODELO,
    VEICULOS.VEI_ANO, VEICULOS.VEI_COR, NOTA_FISCAL.ID_CLIENTES, CLIENTES.CLI_NOME,
    CLIENTES.CLI_ENDEREÇO, CLIENTES.CLI_BAIRRO, CLIENTES.CLI_CIDADE, CLIENTES.CLI_UF
    FROM NOTA_FISCAL JOIN VEICULOS JOIN CLIENTES ON NOTA_FISCAL.ID_VEICULOS = VEICULOS.ID_VEICULOS;
       
   

       
   
